Solved fp2 exercises
MifRea1/study pull request #3
Opened 2019-02-27 19:46 UTC by MifRea1

2019-03-12 10:50 UTC, Andrew8xx8 requested changes

2019-03-12 10:50 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        for e in self
Используй reduce для реализации этой функции

2019-03-12 10:50 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        result = MyArray.new
Используй reduce для реализации этой функции

2019-03-18 11:18 UTC, artempartos commented
👍

2019-03-18 11:18 UTC, artempartos commented
👍

2019-03-18 11:26 UTC, merged